---
sudo: false
language: java
dist: trusty

jdk:
  - oraclejdk8

os:
  - linux

# required to update jdk, there is a compile error with the default version on Travis
addons:
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo $HOME
  - echo $JAVA_OPTS

script:
  - ./gradlew --stacktrace --info assemble test buildPlugin

deploy:
  # deploy develop to the staging environment
  #- provider: script
  #  script: bash scripts/deploy.sh staging
  #  on:
  #    branch: develop
  # deploy master to production
  #- provider: script
  #  script: bash scripts/deploy.sh production
  #  on:
  #    branch: master
